spring.datasource.url=jdbc:postgresql://localhost:5432/billetsystem
spring.datasource.username=billetsystem

spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
server.port=8081